server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bigroot
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        use_sql_comments: true      # SQL 생성시 주석 포함
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: none
    open-in-view: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  tokenExpirationTime: 18000

project:
  folderPath: "files/"


#youtube:
#  api:
#    key: AIzaSyDOvWqy2w9fgR-o1kR0Pwq_UvUTpC4Ud4w
